WindowManager:
    MainWindow:
    PlayGameWindow:
    LiveCalculationWindow:
    CameraWindow:
    CalibrationWindow:
    SettingsWindow:


<MainWindow>:
    name: "Main"

    Button:
        text: "Play game"
        size_hint: 0.5, 0.1
        pos_hint: {"center_x":0.5, "y":0.75}

        on_release:
            root.manager.transition.direction = "left"
            app.root.current = "Play_game"

    Button:
        text: "Live calculations"
        size_hint: 0.5, 0.1
        pos_hint: {"center_x":0.5, "y":0.6}

        on_release:
            root.manager.transition.direction = "left"
            app.root.current = "Live_calculation"

    Button:
        text: "Camera"
        size_hint: 0.5, 0.1
        pos_hint: {"center_x":0.5, "y":0.45}

        on_release:
            root.manager.transition.direction = "left"
            app.root.current = "Camera"

    Button:
        text: "Calibration"
        size_hint: 0.5, 0.1
        pos_hint: {"center_x":0.5, "y":0.3}

        on_release:
            root.manager.transition.direction = "left"
            app.root.current = "Calibration"

    Button:
        text: "Settings"
        size_hint: 0.5, 0.1
        pos_hint: {"center_x":0.5, "y":0.15}

        on_release:
            root.manager.transition.direction = "left"
            app.root.current = "Settings"


<PlayGameWindow>:
    name: "Play_game"
    Button:
        size_hint: 0.5, 0.1
        pos_hint: {"center_x":0.5, "y":0.75}    
        text: "to main"
        on_release:
            root.manager.transition.direction = "right"
            app.root.current = "Main"            
    Button:
        size_hint: 0.5, 0.1
        pos_hint: {"center_x":0.5, "y":0.5}
        text: "Hit me"
        on_release: root.Counter_function()

    Button:
        size_hint: 0.5, 0.1
        pos_hint: {"center_x":0.5, "y":0.3}
        text: "Thread"
        on_release: root.First_thread()

    Button:
        size_hint: 0.5, 0.1
        pos_hint: {"center_x":0.5, "y":0.0}
        text: "Thread"
        on_release: root.test()

    Label:
        size_hint: 0.5, 0.1
        pos_hint: {"center_x":0.5, "y":0.15}
        id: lbl
        text: "Numbers"

<LiveCalculationWindow>:
    name: "Live_calculation"

    Button:
        text: "Go Back"
        on_release:
            root.manager.transition.direction = "right"
            app.root.current = "Main"

<CameraWindow>:
    name: "Camera"
    #slide_text_hue_min: slider_hue_min
    #slide_text_hue_max: slider_hue_max
    #slide_text_sat_min: slider_sat_min
    #slide_text_sat_max: slider_sat_max
    #slide_text_val_min: slider_val_min
    #slide_text_val_max: slider_val_max
    

    Button:
        text: "Go Back"
        size_hint: 0.2, 0.1
        pos_hint: {"center_x":0.15, "y":0.05}
        on_release:
            root.manager.transition.direction = "right"
            app.root.current = "Main"


    Button:
        text: "Apply"
        size_hint: 0.2, 0.1
        pos_hint: {"center_x": 0.85, "y":0.05}
        # Do something - approve change - popup

    Button:
        text: "Last values"
        size_hint: 0.15, 0.075
        pos_hint: {"center_x":0.875, "y":0.5}
        # Load info from file

    Button:
        text: "Blue"
        size_hint: 0.15, 0.075
        pos_hint: {"center_x":0.875, "y":0.4}
        id: btn_blue
        on_press:
            root.btn_blue_press()


            #root.slide_hue_min(*args)
            #root.thread()

    Button:
        text: "Yellow"
        size_hint: 0.15, 0.075
        pos_hint: {"center_x":0.875, "y":0.3}

    Button:
        text: "Green"
        size_hint: 0.15, 0.075
        pos_hint: {"center_x":0.875, "y":0.2}

    BoxLayout:
        orientation: "vertical"
        pos_hint: {"x": 0, "y": 0.6}
        size_hint: 0.8, 0.4

        Label:
            id: hue_min_label
            text: "Hue min: " + str(root.hue_min)
            pos_hint: {"x": 0.6, "y": 0}
            font_size: root.font_size
        Slider:
            min: 0
            max: 179
            id: hue_min_slider
            value: root.hue_min
            step: 1
            orientation: "horizontal"
            on_value: 
                root.slide_hue_min(*args)
                root.thread()
                root.updateImage()
        
        Label:
            id: hue_max_label
            text: "Hue max: " + str(root.hue_max)
            pos_hint: {"x":0.6, "y": 0}
            font_size: root.font_size
        Slider:
            min: 0
            max: 179
            id: hue_max_slider
            value: root.hue_max
            orientation: "horizontal"
            on_value: 
                root.slide_hue_max(*args)
                root.thread()

        Label:
            id: sat_min_label
            text: "Sat min: " + str(root.sat_min)
            pos_hint: {"x":0.6, "y": 0}
            font_size: root.font_size
        Slider:
            min: 0
            max: 255
            id: sat_min_slider
            value: root.sat_min
            orientation: "horizontal"
            on_value: 
                root.slide_sat_min(*args)
                root.thread()

        Label:
            id: sat_max_label
            text: "Sat max: " + str(root.sat_max)
            pos_hint: {"x":0.6, "y": 0}
            font_size: root.font_size
        Slider:
            min: 0
            max: 255
            id: sat_max_slider
            value: root.sat_max
            orientation: "horizontal"
            on_value: 
                root.slide_sat_max(*args)
                root.thread()

        Label:
            id: val_min_label
            text: "Val min: " + str(root.val_min)
            pos_hint: {"x":0.6, "y": 0}
            font_size: root.font_size
        Slider:
            min: 0
            max: 255
            id: val_min_slider
            value: root.val_min
            orientation: "horizontal"
            on_value: 
                root.slide_val_min(*args)
                root.thread()
        
        Label:
            id: val_max_label
            text: "Val max: " + str(root.val_max)
            pos_hint: {"x":0.6, "y": 0}
            font_size: root.font_size
        Slider:
            min: 0
            max: 255
            id: val_max_slider
            value: root.val_max
            orientation: "horizontal"
            on_value: 
                root.slide_val_max(*args)
                root.thread()

    BoxLayout:
        orientation: "vertical"
        pos_hint: {"center_x": 0.5, "y": 0.2}
        size_hint: 0.6, 0.3

        Image:
            source: root.img_src
            id: image
            allow_stretch: False
            keep_ratio: False



<CalibrationWindow>:
    name: "Calibration"

    Button:
        text: "Go Back"
        on_release:
            root.manager.transition.direction = "right"
            app.root.current = "Main"

<SettingsWindow>:
    name: "Settings"

    Button:
        text: "Go Back"
        on_release:
            root.manager.transition.direction = "right"
            app.root.current = "Main"

